# Generated by Django 6.0.7 on 2026-07-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='Primary personal bio introduction text')),
                ('career_objective', models.TextField(blank=True, help_text='Optional career objective text block')),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order sequence index')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('duration', models.CharField(help_text='e.g. Present or Completed', max_length=100)),
                ('description', models.TextField(help_text='Key responsibilities and achievements')),
                ('order', models.IntegerField(default=0, help_text='Display order sequence index')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. AIML Student & Future Full Stack Developer', max_length=200)),
                ('subtitle', models.TextField(help_text='Detailed intro sentence or sub-header description')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, help_text='Deployed live demo URL')),
                ('tech_stack', models.CharField(help_text='Comma-separated technology stack list, e.g. React, Tailwind CSS', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order sequence index')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Languages', 'Languages'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=100, help_text='Proficiency percentage, e.g. 0 to 100')),
                ('icon', models.ImageField(blank=True, help_text='Optional skill vector graphic/icon', null=True, upload_to='skills/')),
            ],
        ),
    ]
