# Generated by Django 6.0.7 on 2026-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. AWS Certified Solutions Architect', max_length=200)),
                ('issuing_organization', models.CharField(help_text='e.g. Amazon Web Services, Coursera, Google', max_length=150)),
                ('issue_date', models.CharField(blank=True, help_text='e.g. 2024 or Issued Jan 2024', max_length=100)),
                ('credential_url', models.URLField(blank=True, help_text='Verification link or PDF link')),
                ('description', models.TextField(blank=True, help_text='Brief summary of skills verified by this certification')),
                ('order', models.IntegerField(default=0, help_text='Display order sequence index')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('AI & ML', 'AI & ML'), ('Database', 'Database'), ('Tools', 'Tools'), ('Certifications', 'Certifications')], max_length=50),
        ),
    ]
