# Generated by Django 6.0.7 on 2026-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug, e.g. getting-started-with-django-react', max_length=200, unique=True)),
                ('author', models.CharField(default='Ankit Kumar', max_length=100)),
                ('summary', models.TextField(help_text='Brief excerpt/summary for card previews')),
                ('content', models.TextField(help_text='Full article content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('tags', models.CharField(help_text='Comma-separated tags, e.g. React, AI, Django', max_length=255)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
